version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - mynet

  keycloak:
    container_name: keycloak
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    image: jboss/keycloak
    expose:
      - ${KEYCLOAK_PORT}
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    restart: unless-stopped
    command:
      - "-b 0.0.0.0"
      - "-Djboss.http.port=${KEYCLOAK_PORT}"
    networks:
      - mynet

  backend-service:
    container_name: url-shortner-backend-service
    image: suraj362/url-shortner-backend-service:latest
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_AUTH_URL=${KEYCLOAK_AUTH_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - SERVER_PORT=${BACKEND_SERVER_PORT}
      - REDIS_HOST=redis
    ports:
      - ${BACKEND_SERVER_PORT}:${BACKEND_SERVER_PORT}
    volumes:
      - backendapp:/app
    depends_on:
      - db
      - keycloak
      - redis
    networks:
      - mynet
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - mynet
  redirect-service:
    container_name: url-shortner-redirect-service
    image: suraj362/url-shortner-redirect-service:latest
    restart: unless-stopped
    volumes:
      - redirectapp:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${REDIRECT_SERVER_PORT}
    ports:
      - ${REDIRECT_SERVER_PORT}:${REDIRECT_SERVER_PORT}
    expose:
      - ${REDIRECT_SERVER_PORT}
    depends_on:
      - db
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  db:
    driver: local
  backendapp:
  redirectapp:
